### PR TITLE
Drops tSNE table no longer needed

### PR DESCRIPTION
**Pull request by pcm32**
This PR drops the tSNE table. To be merged only once the new UMAP setup is working on public/fallback out of caution.

### CODE REVIEW

**Comment by pcm32** [comment]
This will probably require a move to github actions...

**Review by pinin4fjords — APPROVED** [review]
LGTM

**Review by haideriqbal — APPROVED** [review]
LGTM!

**Comment by pcm32** [comment]
Thanks guys, out of caution we wait until UMAP release is on public to avoid any accidental spill overs (once merged, someone could apply this inadvertently on public/fallback).

**Comment by alfonsomunozpomer** [comment]
A couple of things:
- This will need to be accompanied with the removal of this line: https://github.com/ebi-gene-expression-group/db-scxa/blob/develop/bin/delete_db_scxa_dimred.sh#L9 (plus any tests affected)
- On a more general note, since we use Flyway+Postgres container to create the a DB from scratch, the `db` directory in this repo is no longer needed, which just leaves us with the `flyway` directory which is split among bulk and single-cell. I think it would make sense to move the SC migrations to `db-scxa` and the bulk ones to a bulk repo.

**Comment by pcm32** [comment]
Agreed @alfonsomunozpomer, we had written a story for the first point, maybe I should have mentioned it here:
https://www.pivotaltracker.com/story/show/179102575

Regarding the second point, I cannot think of any reason why not to refactor like that, db-scxa already imports this as a submodule, and given that schema and loading logic are highly coupled, versioning on the same repo should be alright. Any opposition @pinin4fjords ?

I would still suggest that we do this refactoring past urgencies and holiday period :-), so probably past mid September.

**Comment by pinin4fjords** [comment]
Sure, will save us a step in updating submodule pins- but yep, for later.

**Comment by pcm32** [comment]
UMAP has been released to public, so merging this now.

**Pull request merged**
